### ISSUE TITLE
✨ Port and display `libmacchina::traits::GeneralReadout::disk_space()`

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/macchina#148]
@123marvin123 added a new readout which can query the disk usage of the `/` partition.

You might want to display the disk usage of other partitions, and don't worry, we'll definitely give you the option to.

# Todo
- [x] Port and display `libmacchina::traits::GeneralReadout::disk_space()`
- [ ] Convert to bars.
- [ ] Add a configuration option so one can specify which partition to query
- [ ] Memory and disk usage should have uniform output; use `byte-unit` crate for both readouts, removing `bytesize` dependency.
- [x] Standardize libmacchina's API so macchina doesn't have to accommodate for its methods' inconsistent return types (not yet merged, [learn more](https://github.com/Macchina-CLI/libmacchina/tree/standardize-api))
- [ ] Fix memory's incorrect unit, but correct calculations.
# Configuration
The user should be able to specify whatever partition they want. _Freedom!_
